spring.application.name=workflow-system
spring.datasource.url=jdbc:mysql://localhost:3306/workflowdb
spring.datasource.username=root
spring.datasource.password=santhosh@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
